baseURL = "https://lee-hill-johnston.netlify.com/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "site-theme"
title = "Lee, Hill and Johnston Insurors"
[mediaTypes."text/noExt"]
suffixes = ""
[[menu.desktop]]
identifier = "lifeInsurance"
name = "Life and Health Insurance"
parent = "ourProducts"
url = "/products/life-insurance/life-insurance/"
weight = 3
[[menu.desktop]]
identifier = "businessInsurance"
name = "Business Insurance"
parent = "ourProducts"
url = "/products/business/business-liability/"
weight = 2
[[menu.desktop]]
identifier = "personalInsurance"
name = "Personal Insurance"
parent = "ourProducts"
url = "/products/personal/auto-insurance/"
weight = 1
[[menu.desktop]]
identifier = "companiesRepresented"
name = "Companies We Represent"
parent = "ourCompany"
url = "/companies-we-represent/"
weight = 4
[[menu.desktop]]
identifier = "ourHistory"
name = "Our History"
parent = "ourCompany"
url = "/our-history/"
weight = 3
[[menu.desktop]]
identifier = "ourCompany1"
name = "Our Company"
parent = "ourCompany"
url = "/our-company/"
weight = 2
[[menu.desktop]]
identifier = "ourTeam"
name = "Our Team"
parent = "ourCompany"
url = "/our-team/"
weight = 1
[[menu.desktop]]
identifier = "contactUs"
name = "Contact Us"
url = "/contact-us/"
weight = 4
[[menu.desktop]]
identifier = "faqs"
name = "FAQs"
url = "/insurance-faqs/"
weight = 3
[[menu.desktop]]
identifier = "ourProducts"
name = "Our Products"
post = "hover"
url = "#"
weight = 2
[[menu.desktop]]
identifier = "ourCompany"
name = "Our Company"
post = "hover"
url = "#"
weight = 1
[[menu.mobile]]
identifier = "lifeInsurance"
name = "Life and Health Insurance"
parent = "ourProducts"
url = "/products/life-insurance/life-insurance/"
weight = 3
[[menu.mobile]]
identifier = "businessInsurance"
name = "Business Insurance"
parent = "ourProducts"
url = "/products/business/business-liability/"
weight = 2
[[menu.mobile]]
identifier = "personalInsurance"
name = "Personal Insurance"
parent = "ourProducts"
url = "/products/personal/auto-insurance/"
weight = 1
[[menu.mobile]]
identifier = "companiesRepresented"
name = "Companies We Represent"
parent = "ourCompany"
url = "/companies-we-represent/"
weight = 4
[[menu.mobile]]
identifier = "ourHistory"
name = "Our History"
parent = "ourCompany"
url = "/our-history/"
weight = 3
[[menu.mobile]]
identifier = "ourCompany1"
name = "Our Company"
parent = "ourCompany"
url = "/our-company/"
weight = 2
[[menu.mobile]]
identifier = "ourTeam"
name = "Our Team"
parent = "ourCompany"
url = "/our-team/"
weight = 1
[[menu.mobile]]
identifier = "quote"
name = "Get a Quote"
url = "/quote/"
weight = 5
[[menu.mobile]]
identifier = "contactUs"
name = "Contact Us"
url = "/contact-us/"
weight = 4
[[menu.mobile]]
identifier = "faqs"
name = "FAQs"
url = "/insurance-faqs/"
weight = 3
[[menu.mobile]]
identifier = "ourProducts"
name = "Our Products"
post = "hover"
url = "#"
weight = 2
[[menu.mobile]]
identifier = "ourCompany"
name = "Our Company"
post = "hover"
url = "#"
weight = 1
[outputFormats.insurance-faqs]
baseName = "insurance-faqs"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.redirects]
baseName = "_redirects"
isPlainText = true
mediaType = "text/noExt"
path = "/"
[outputFormats.sitemapindex]
baseName = "sitemapindex"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.sitepages]
baseName = "sitepages"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.siteposts]
baseName = "siteposts"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputs]
home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "insurance-faqs"]
[params.Logos]
dark_logo = "/pageimg/example-logo.png"
footer_logo = "/pageimg/footer-logo.png"
logo = "/pageimg/logo.png"
mobile_logo = "/pageimg/logo.png"
[params.address]
city = "Statesboro"
state = "GA"
street = "P.O. Box 134"
zip = 30459
[params.algolia]
appId = ""
index_name = ""
search_key = ""
[params.contact_numbers]
Fax = "555.555.5555"
Phone = "555.555.5555"
[params.email]
email = "example@example.com"
[params.extra_tools]
algolia_search = false
floating_header = false
font_awesome = true
[params.meta]
description = "Whether it’s home or auto, business risk management, or life/health insurance, we’ve built a reputation over the past 50 years for insuring the trust of thousands across the Southeast. Let us do the same for you."
[params.publishing_settings]
site_in_production = true
[params.social_links]
facebook = ""
insta = ""
linkedin = ""
pinterest = ""
[params.tracking]
cloudinaryUrl = ""
google_analytics = "UA-121813241-28"
[params.utility_images]
thank_you_background = "/pageimg/thank-you-contact.jpg"
[sitemap]
filename = "sitepages.xml"
