baseURL = "https://lee-hill-johnston.netlify.com/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "site-theme"
title = "Lee, Hill and Johnston Insurors"
[mediaTypes."text/noExt"]
suffixes = ""
[[menu.desktop]]
identifier = "Life and Health Insurance"
name = "Life and Health Insurance"
parent = "Our Products"
url = "/products/life-insurance/life-insurance/"
weight = 3
[[menu.desktop]]
identifier = "Business Insurance"
name = "Business Insurance"
parent = "Our Products"
url = "/products/business/business-liability/"
weight = 2
[[menu.desktop]]
identifier = "Personal Insurance"
name = "Personal Insurance"
parent = "Our Products"
url = "/products/personal/auto-insurance/"
weight = 1
[[menu.desktop]]
identifier = "Companies We Represent"
name = "Companies We Represent"
parent = "Our Company"
url = "/companies-we-represent/"
weight = 4
[[menu.desktop]]
identifier = "Our History"
name = "Our History"
parent = "Our Company"
url = "/our-history/"
weight = 3
[[menu.desktop]]
identifier = "Our Company 1"
name = "Our Company"
parent = "Our Company"
url = "/our-company/"
weight = 2
[[menu.desktop]]
identifier = "Our Team"
name = "Our Team"
parent = "Our Company"
url = "/our-team/"
weight = 1
[[menu.desktop]]
identifier = "Contact Us"
name = "Contact Us"
url = "/contact-us/"
weight = 4
[[menu.desktop]]
identifier = "FAQs"
name = "FAQs"
url = "/insurance-faqs/"
weight = 3
[[menu.desktop]]
identifier = "Our Products"
name = "Our Products"
post = "hover"
url = "#"
weight = 2
[[menu.desktop]]
identifier = "Our Company"
name = "Our Company"
post = "hover"
url = "#"
weight = 1
[[menu.mobile]]
identifier = "Life and Health Insurance"
name = "Life and Health Insurance"
parent = "Our Products"
url = "/products/life-insurance/life-insurance/"
weight = 3
[[menu.mobile]]
identifier = "Business Insurance"
name = "Business Insurance"
parent = "Our Products"
url = "/products/business/business-liability/"
weight = 2
[[menu.mobile]]
identifier = "Personal Insurance"
name = "Personal Insurance"
parent = "Our Products"
url = "/products/personal/auto-insurance/"
weight = 1
[[menu.mobile]]
identifier = "Companies We Represent"
name = "Companies We Represent"
parent = "Our Company"
url = "/companies-we-represent/"
weight = 4
[[menu.mobile]]
identifier = "Our History"
name = "Our History"
parent = "Our Company"
url = "/our-history/"
weight = 3
[[menu.mobile]]
identifier = "Our Company 1"
name = "Our Company"
parent = "Our Company"
url = "/our-company/"
weight = 2
[[menu.mobile]]
identifier = "Our Team"
name = "Our Team"
parent = "Our Company"
url = "/our-team/"
weight = 1
[[menu.mobile]]
identifier = "Get a Quote"
name = "Get a Quote"
url = "/quote/"
weight = 5
[[menu.mobile]]
identifier = "Contact Us"
name = "Contact Us"
url = "/contact-us/"
weight = 4
[[menu.mobile]]
identifier = "FAQs"
name = "FAQs"
url = "/insurance-faqs/"
weight = 3
[[menu.mobile]]
identifier = "Our Products"
name = "Our Products"
post = "hover"
url = "#"
weight = 2
[[menu.mobile]]
identifier = "Our Company"
name = "Our Company"
post = "hover"
url = "#"
weight = 1
[outputFormats.insurance-faqs]
baseName = "insurance-faqs"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.redirects]
baseName = "_redirects"
isPlainText = true
mediaType = "text/noExt"
path = "/"
[outputFormats.sitemapindex]
baseName = "sitemapindex"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.sitepages]
baseName = "sitepages"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.siteposts]
baseName = "siteposts"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputs]
home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "insurance-faqs"]
[params.algolia]
appId = ""
index_name = ""
search_key = ""
[params.extra_tools]
algolia_search = false
floating_header = false
font_awesome = true
[params.publishing_settings]
site_in_production = true
[params.tracking]
cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"
[params.utility_images]
thank_you_background = "/pageimg/thank-you-contact.jpg"
[sitemap]
filename = "sitepages.xml"