---
new_page_extension: md
auto_deploy: false
admin_path: "/static/inside"
webhook_url: 
sections:
- type: document
  path: themes/site-theme/data/global_data.toml
  label: Site Settings
- type: directory
  path: content
  label: Home Page
  create: all
  match: "*"
- type: directory
  path: content/pages
  label: Inner Pages
  create: all
  match: "**/*"
  exclude: team.md thank-you.md
- type: directory
  path: content/companies
  label: Companies
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - company
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - product
- type: directory
  path: content/faqs
  label: Faqs
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - faq
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
  new_doc_ext: _index.md
  templates:
  - team-member
upload_dir: Lee, Hill and Johnston
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
