---
label: Product
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: type
  label: type
- type: text
  name: title
  label: title
- type: text
  name: page_status
  label: page_status
- type: text
  name: publish_image
  label: publish_image
- type: text
  name: meta_description
  label: meta_description
- type: text
  name: insurance_type
  label: insurance_type
- type: file
  name: navigation_image
  label: navigation_image
